<template>
  <div class="max-w-7xl mx-auto pt-3 px-4 sm:px-6 lg:px-8">
    <!-- Title -->
    <h1
      class="text-lg font-semibold tracking-widest text-gray-900 uppercase dark-mode:text-white"
    >
      All Users/Moderators
    </h1>
    <!-- End Title -->
  </div>
  <jet-bar-container>
    <jet-bar-alert
      v-on:click="removeAlertData()"
      v-show="alert_status"
      :text="alertmessage"
      :type="type"
    />
    <!--     <jet-bar-stats-container>
      <jet-bar-stat-card title="Total clients" number="6389" type="warning">
        <template v-slot:icon>
          <jet-bar-icon type="users" fill />
        </template>
      </jet-bar-stat-card>

      <jet-bar-stat-card title="Account balance" number="$ 46,760.89" type="success">
        <template v-slot:icon>
          <jet-bar-icon type="money" fill />
        </template>
      </jet-bar-stat-card>

      <jet-bar-stat-card title="New sales" number="376" type="info">
        <template v-slot:icon>
          <jet-bar-icon type="cart" fill />
        </template>
      </jet-bar-stat-card>

      <jet-bar-stat-card title="Pending contacts" number="35" type="danger">
        <template v-slot:icon>
          <jet-bar-icon type="message" fill />
        </template>
      </jet-bar-stat-card>
    </jet-bar-stats-container> -->
    <select v-model="selected" v-on:change="getUsers()">
      <option value="users">Users</option>
      <option value="moderators">Moderators</option>
    </select>
    <jet-secondary-button
      v-on:click="generateUsers()"
      v-if="selected == 'users'"
      class="py-2 px-4 mx-2 bg-green-400 cursor-pointer"
    >
      Download all Vouchers
    </jet-secondary-button>
    <component-user
      v-if="users"
      :users="users"
      :selected="selected"
      @paginate="paginate2($event)"
      @novoucher="alertData(true, 'No Voucher Code Generated by the User', 'danger')"
    />
  </jet-bar-container>
</template>

<script>
import JetBarContainer from "@/Components/JetBarContainer";
import JetBarAlert from "@/Components/JetBarAlert";
import JetBarStatsContainer from "@/Components/JetBarStatsContainer";
import JetBarStatCard from "@/Components/JetBarStatCard";
import JetBarTable from "@/Components/JetBarTable";
import JetBarTableData from "@/Components/JetBarTableData";
import JetBarBadge from "@/Components/JetBarBadge";
import JetBarIcon from "@/Components/JetBarIcon";
import ComponentUser from "@/MyComponents/ComponentUser";
import JetSecondaryButton from "@/Jetstream/SecondaryButton";

export default {
  components: {
    JetBarContainer,
    JetBarAlert,
    JetBarStatsContainer,
    JetBarStatCard,
    JetBarTable,
    JetBarTableData,
    JetBarBadge,
    JetBarIcon,
    ComponentUser,
    JetSecondaryButton,
  },
  props: ["profiled"],
  mounted() {
    this.getUsers();
  },
  data() {
    return {
      users: [],
      selected: "users",
      alert_status: false,
      alertmessage: "",
      type: "info",
    };
  },
  methods: {
    generateUsers() {
      axios
        .post(route("admin.generate_users"), {}, { responseType: "blob" })
        .then((res) => {
          console.log(res.data);
          var fileURL = window.URL.createObjectURL(new Blob([res.data]));
          var fileLink = document.createElement("a");

          fileLink.href = fileURL;
          fileLink.setAttribute("download", "All User Vouchers.xlsx");
          document.body.appendChild(fileLink);

          fileLink.click();
        });
    },
    getUsers() {
      axios
        .get(route("admin.get_user", this.selected))
        .then((res) => {
          this.users = res.data;
        })
        .catch((e) => {
          console.log(e);
        });
    },
    paginate2(href) {
      axios
        .get(href + "&&group_name=" + this.group_name)
        .then((res) => {
          this.users = res.data;
          if (this.users.total == 0) {
            this.alertData(true, "No data fetched.", "danger");
          }
        })
        .catch((e) => {
          this.alertData(
            true,
            "Unable to Retrieve Data: Insufficient Permission/Server Error",
            "danger"
          );
        });
    },
    alertData(status, message, type) {
      this.alert_status = status;
      this.alertmessage = message;
      this.type = type;
      setInterval(
        function () {
          this.removeAlertData();
        }.bind(this),
        2500
      );
    },
    removeAlertData() {
      this.alert_status = false;
      this.alertmessage = "";
      this.type = "info";
    },
  },
};
</script>
